### ISSUE TITLE
when searching for concepts, spaces are not allowed

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#11]
When searching for concepts, spaces are not recognized by the concept search so I cannot drill down to the desired entry. For example, if I want 'Temperature Gradient Probe' I can search for 'temperature' and all concepts that start with 'temperature' show up, however when I add the space only 'temperature' shows and if I add a 'g' (for gradient) a new search begins with 'G' concepts.

**Comment by hohonuuli** [comment]
I'll have to look into this a bit. Spaces currently reset the concept search.

**Comment by hohonuuli** [comment]
Hmmm, not sure that I will be able to fix this. This is an issue with JavaFX. <https://bugs.openjdk.java.net/browse/JDK-8087549>

**Comment by hohonuuli** [comment]
Here's the troublesome sequence of events:

1. The space is pressed
2. The combobox closes it's drop down
3. The combobox consumes the space, so it's not reaching any key listeners that I register
4. When the drop down is closed, my code resets the filter used for constraining the search.

One work around is to switch the filter from using a `startsWith` that completely ignores spaces. So you just keep typing characters but skip spaces. So type `pandalusplaceros` instead of `pandalus platyceros`. I'll add that and we'll see how it works.

**Comment by hohonuuli** [comment]
I _think_ this will resolve the issue. Closing this. We can reopen if needed.
