### ISSUE TITLE
Inconsistent entry of annotations

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#47]
Using the VARS anno GUI that was released today, entering annotations is very inconsistent. After typing in the concept name, it takes 1, 2, or 3 presses of the enter button for the annotation to 'stick.' When it takes 2-3+ presses of the enter button, VARS becomes very hard to use.

**Comment by hohonuuli** [comment]
I _think_ this is what's going on. Caching of concept data is now handled differently. Previously, a process was running in the background that loaded the entire knowledgebase piece-by-piece. This was done mainly in order to fetch the alternate names for a concept. It tends to put a stress on the vars-kb-server microservice. Now, the first time you use a concept, the annotation app makes a call to fetch from the microservice, then caches it. Much more efficient, but makes for slower response times.

The code for making the call is in [AnnotationEditorPaneController](https://github.com/mbari-media-management/vars-annotation/blob/master/src/main/java/org/mbari/m3/vars/annotation/ui/roweditor/AnnotationEditorPaneController.java#L156).  This, is in turn, making call into [CacheConceptService2](https://github.com/mbari-media-management/vars-annotation/blob/master/src/main/java/org/mbari/m3/vars/annotation/services/CachedConceptService2.java#L80). 

With the new load path for concept-names, I don't need to call findDetails in the ConceptService. I'll replace this with a call to findConcept instead as a Concept should now contain the alternative names.

**Comment by hohonuuli** [comment]
New release tagged and built.

**Comment by hohonuuli** [comment]
Most of the fix is in [CachedConceptService3.java](https://github.com/mbari-media-management/vars-annotation/blob/master/src/main/java/org/mbari/m3/vars/annotation/services/CachedConceptService3.java)
