### ISSUE TITLE
Usability: New observation puts cursor into naming field

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#87]
When an new observation is made (by clicking new or by taking a framegrab) user has to use the mouse to click into the field to start naming it. Jump the cursor there automatically.

**Comment by hohonuuli** [comment]
__When a new observation is made (either by new or framegrab), the observation combobox actually has focus. You just can start typing right away.__  I've tested and verified that this is the current behavior.

I think the confusion is because there's no visual element indicating it has focus. (i.e. the red underline). There's a glitch in the underlying JavaFX CSS library that's preventing the focus indicator from appearing; likely related to the borderpane layout manger being used.

**Comment by lindakuhnz** [comment]
But I've tried to start typing and it cannot be done until you mouse click into the area.

**Comment by lindakuhnz** [comment]
Hmmm. Something is inconsistent. Will continue to test.

**Comment by hohonuuli** [comment]
I have a telecon in a few minutes. I'll come down and take a look when it's done.
